### ISSUE TITLE
Sample Program

### ISSUE THREAD

**Issue by rahulcoode90** [dorkbox/CabParser#2]
Hi,
Can you provide a sample program on what all parameters has to be passed to program to decompress a cab file.

Thanks

**Comment by dorkbox** [comment]
This is how I use it.

````
PE pe = new PE(fileName);
// System.err.println(pe.getInfo());

ByteArrayInputStream cab = pe.getLargestResourceAsStream();

ByteArrayOutputStream extractedStream = null;
try {
    CabParser cabParser = new CabParser(cab, cabName);
    extractedStream = cabParser.extractStream();
} catch (CabException e) {
    e.printStackTrace();
    return null;
}

// now we have the zip file to use!!
if (extractedStream != null) {
    ByteArrayInputStream byteOutputStream = new  ByteArrayInputStream(extractedStream.toByteArray());
    return new ZipInputStream(byteOutputStream);
}
else {
    return null;
}
````

**Comment by rahulcoode90** [comment]
What is PE ?

**Comment by dorkbox** [comment]
https://github.com/dorkbox/PeParser

Only necessary if you are trying to get resources out of a windows executable.

**Comment by rahulcoode90** [comment]
I just want to extract the data/file from a cab file.

**Comment by dorkbox** [comment]
That was the example of how I use it.... Since you want something different, you'll have to write your own code. The first parameter for CabParser is `InputStream`. A `FileInputStream` should do the trick.

**Comment by zloykrys** [comment]
hi mate,

could you please give an example of reading all folders and files from the cab file and extracting them. I'm trying to use your example above:

`String cab_file_name = args[0];
FileInputStream cabfile = new FileInputStream(cab_file_name);
ByteArrayOutputStream extractedStream = null;
CabParser cabParser = new CabParser(cabfile, cab_file_name);

/* reading list of files - works fine */
for (int i = 0; i < cabParser.header.cFiles; i++) {
                // print all files
                System.out.println(cabParser.files[i].szName);
            }

`

So far I was able to get a list of files (not folders) from the CAB file, but not sure how to extract them. Also as some files are in folders, I think the folders need to go first and should be created prior to extracting files. Is it something that can be achieved with your library?

Many thanks.

**Comment by dorkbox** [comment]
@zloykrys Not exactly. This library was specifically made to extract a single file, and for my use it extracts the java runtime from a windows executable. It can do a lot more, but that was it's designed purpose.

If you are wanting to extract all of the files from a cab, you would likely have to create the folders manually, then extract each one to that location. The files are at `cabParser.files` and the folders are at `cabParser.folders`, or at `cabParser.header.cFolders` if you wanted to use that data structure.

I don't have an example (and really don't have time to write one), but you can see how it works [here @ Line112](https://github.com/dorkbox/CabParser/blob/master/src/dorkbox/cabParser/CabParser.java#L112)

If you come up with something to improve this process, I'll happily take contributions.
